osx_image: xcode8
language: objective-c
notifications:
  email: false
before_install:
- gem install bundler
- bundle install
- git remote set-url origin "https://${GITHUB_TOKEN}@github.com/carambalabs/SugarRecord.git"
script:
- bundle exec fastlane travis
after_success:
  - bash <(curl -s https://codecov.io/bash)